name: firebase_app_check_example
description: Firebase App Check example application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cloud_firestore:
    path: ../../../cloud_firestore/cloud_firestore
  cupertino_icons: ^0.1.2
  firebase_app_check:
    path: ../
  firebase_core:
    path: ../../../firebase_core/firebase_core
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
