name: firebase_database_example
description: Demonstrates how to use the firebase_database plugin.

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  firebase_core: ^3.4.1
  firebase_database: ^11.1.2
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
