# Copyright 2022, the Chromium project authors.  Please see the AUTHORS file
# for details. All rights reserved. Use of this source code is governed by a
# BSD-style license that can be found in the LICENSE file.

# Configuration for move-issues - https://github.com/dessant/move-issues

# Delete the command comment when it contains no other content.
deleteCommand: true

# Close the source issue after moving.
closeSourceIssue: true

# Lock the source issue after moving.
lockSourceIssue: false

# Mention issue and comment authors.
mentionAuthors: true

# Preserve mentions in the issue content.
keepContentMentions: true
