name: firebase_core_platform_interface
description: A common platform interface for the firebase_core plugin.
homepage: https://github.com/firebase/flutterfire/tree/master/packages/firebase_core/firebase_core_platform_interface
repository: https://github.com/firebase/flutterfire/tree/master/packages/firebase_core/firebase_core_platform_interface
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 4.8.0

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  collection: ^1.17.1
  flutter:
    sdk: flutter
  # Needed to export the mocks
  flutter_test:
    sdk: flutter
  meta: ^1.9.1
  plugin_platform_interface: ^2.1.4

dev_dependencies:
  mockito: ^5.4.2
  pigeon: ^10.1.3
