name: firebase_data_connect
description: "Firebase Data Connect"
version: 0.1.0+1
homepage: https://firebase.google.com/docs/data-connect/quickstart?platform=flutter

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  firebase_app_check: ^0.2.2+6
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.1
  firebase_core_platform_interface: ^5.0.0
  flutter:
    sdk: flutter
  google_generative_ai: ^0.4.0
  grpc: ^3.2.4
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.10
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mockito: ^5.0.0
  plugin_platform_interface: ^2.1.3
