name: firebase_core_example
description: Demonstrates how to use the firebase_core plugin.

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  firebase_core:
    path: ../
  flutter:
    sdk: flutter

dependency_overrides:
  quiver: ">=3.0.0-nullsafety.2 <4.0.0"

dev_dependencies:
  e2e: ^0.6.1
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
