name: firebase_performance_platform_interface
description: A common platform interface for the firebase_performance plugin.
version: 0.2.0
homepage: https://firebase.google.com/docs/perf-mon/flutter/get-started

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  _flutterfire_internals: ^1.3.47
  firebase_core: ^3.8.1
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.3

dev_dependencies:
  firebase_core_platform_interface: ^6.0.0
  flutter_test:
    sdk: flutter
