name: firebase_storage_example
description: Demonstrates how to use the firebase_storage plugin.

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.2
  flutter:
    sdk: flutter
  image_picker: ^1.0.2
  image_picker_for_web: ^2.1.12
  web: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/hello.txt
