name: cloud_firestore_platform_interface
description: A common platform interface for the cloud_firestore plugin.
version: 5.15.3
homepage: https://github.com/firebase/flutterfire/tree/master/packages/cloud_firestore/cloud_firestore_platform_interface
repository: https://github.com/firebase/flutterfire/tree/master/packages/cloud_firestore/cloud_firestore_platform_interface

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  _flutterfire_internals: ^1.3.4
  collection: ^1.17.1
  firebase_core: ^2.15.0
  flutter:
    sdk: flutter
  meta: ^1.9.1
  plugin_platform_interface: ^2.1.4

dev_dependencies:
  firebase_core_platform_interface: ^4.8.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
