name: cloud_firestore_odm_example
version: 1.0.0-dev.1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cloud_firestore:
    path: ../../../cloud_firestore/cloud_firestore
  cloud_firestore_odm:
    path: ../../cloud_firestore_odm
  firebase_core:
    path: ../../../firebase_core/firebase_core
  flutter:
    sdk: flutter
  freezed_annotation: ^2.0.0
  json_annotation: ^4.6.0
  meta: ^1.3.0

dev_dependencies:
  build_runner: ^2.0.0
  cloud_firestore_odm_generator:
    path: ../../cloud_firestore_odm_generator
  cloud_firestore_odm_generator_integration_test:
    path: ../../cloud_firestore_odm_generator/cloud_firestore_odm_generator_integration_test
  flutter_test:
    sdk: flutter
  freezed: ^2.0.0
  http: ^0.13.5
  integration_test:
    sdk: flutter
  json_serializable: ^6.3.0
  mockito: ^5.0.0

flutter:
  uses-material-design: true
