name: cloud_functions_example
description: Demonstrates how to use the cloud_functions plugin.
author: Flutter Team <flutter-dev@googlegroups.com>

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  cloud_functions:
    path: ..
  firebase_core: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  e2e: ^0.2.0

flutter:
  uses-material-design: true

