name: tests_mobile
description: FlutterFire integration testing app.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore:
    path: ../packages/cloud_firestore/cloud_firestore
  firebase_core:
    path: ../packages/firebase_core/firebase_core
  cupertino_icons: ^0.1.3

dependency_overrides:
  firebase_core:
    path: ../packages/firebase_core/firebase_core

  firebase_core_platform_interface:
    path: ../packages/firebase_core/firebase_core_platform_interface

  cloud_firestore_platform_interface:
    path: ../packages/cloud_firestore/cloud_firestore_platform_interface

dev_dependencies:
  e2e: ^0.4.0
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
