name: firebase_storage_platform_interface
description: A common platform interface for the firebase_storage plugin.
version: 4.4.4
homepage: https://github.com/firebase/flutterfire/tree/master/packages/firebase_storage/firebase_storage_platform_interface
repository: https://github.com/firebase/flutterfire/tree/master/packages/firebase_storage/firebase_storage_platform_interface
environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  collection: ^1.17.1
  firebase_core: ^2.15.0
  flutter:
    sdk: flutter
  meta: ^1.9.1
  plugin_platform_interface: ^2.1.4

dev_dependencies:
  firebase_core_platform_interface: ^4.8.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
