name: firebase_in_app_messaging_example
description: Demonstrates how to use the firebase_in_app_messaging plugin.
publish_to: 'none'

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  firebase_analytics: ^11.3.4
  firebase_core: ^3.7.0
  firebase_in_app_messaging: ^0.8.0+9
  firebase_in_app_messaging_platform_interface: ^0.2.4+45
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
