name: firebase_in_app_messaging_example
description: Demonstrates how to use the firebase_in_app_messaging plugin.
publish_to: 'none'

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  firebase_analytics: ^12.0.0
  firebase_core: ^3.9.0
  firebase_in_app_messaging: ^0.9.0
  firebase_in_app_messaging_platform_interface: ^0.3.0
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
