name: firebase_app_check_web
description: The web implementation of firebase_auth
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_app_check/firebase_app_check_web
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.4"

dependencies:
  firebase_auth_platform_interface: ^4.2.0
  firebase_core: ^1.1.0
  firebase_core_web: ^1.0.2
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http_parser: ^4.0.0
  intl: ^0.17.0
  js: ^0.6.3
  meta: ^1.3.0

dev_dependencies:
  firebase_app_check:
    path: ../firebase_app_check
  firebase_core_platform_interface: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseAppCheckhWeb
        fileName: firebase_app_check_web.dart
