name: firebase_auth_example
description: Demonstrates how to use the firebase_auth plugin.
author: Flutter Team <flutter-dev@googlegroups.com>

dependencies:
  flutter:
    sdk: flutter
  firebase_auth:
    path: ../
  firebase_auth_web:
    path: ../../firebase_auth_web
  google_sign_in: ^4.0.0
  firebase_core: ^0.4.0+8
  firebase_core_web: ^0.1.0
  firebase_dynamic_links: ^0.3.0
  uuid: ^2.0.2

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true
