name: cloud_functions_example
description: Demonstrates how to use the cloud_functions plugin.

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.12.13+hotfix.4 <2.0.0"
  
dependencies:
  cloud_functions:
    path: ../
  cupertino_icons: ^0.1.2
  firebase_core:
    path: ../../../firebase_core/firebase_core
  flutter:
    sdk: flutter

dependency_overrides:
  firebase_core:
    path: ../../../firebase_core/firebase_core
  firebase_core_platform_interface:
    path: ../../../firebase_core/firebase_core_platform_interface

dev_dependencies:
  drive: 0.0.1-6.0.pre
  e2e: ^0.6.1
  flutter_driver:
    sdk: flutter
  pedantic: ^1.8.0
  test: any

flutter:
  uses-material-design: true
