name: firebase_crashlytics_example
description: Demonstrates how to use the firebase_crashlytics plugin.

environment:
  sdk: '>=2.16.0 <3.0.0'
  flutter: '>=1.12.13+hotfix.5'

dependencies:
  firebase_analytics:
    path: ../../../firebase_analytics/firebase_analytics
  firebase_core:
    path: ../../../firebase_core/firebase_core
  firebase_crashlytics:
    path: ../
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
