name: firebase_crashlytics_example
description: Demonstrates how to use the firebase_crashlytics plugin.

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  firebase_analytics: ^11.3.5
  firebase_core: ^3.8.0
  firebase_crashlytics: ^4.1.5
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
