name: firebase_performance
description: Flutter plugin for Google Performance Monitoring for Firebase, an app
  measurement solution that monitors traces and HTTP/S network requests on Android and
  iOS.
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_performance
# 0.3.y+z is compatible with 1.0.0, if you land a breaking change bump
# the version to 2.0.0.
# See more details: https://github.com/flutter/flutter/wiki/Package-migration-to-1.0.0
version: 0.3.1+9

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.8.0
  e2e: ^0.2.1
  http: ^0.12.0
  flutter_test:
    sdk: flutter
  firebase_core: ^0.4.0
  flutter_driver:
    sdk: flutter
  test: any

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebaseperformance
        pluginClass: FirebasePerformancePlugin
      ios:
        pluginClass: FLTFirebasePerformancePlugin

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"
