name: firebase_messaging_web
description: The web implementation of firebase_messaging
version: 0.1.0
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging_web

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseMessagingWeb
        fileName: firebase_messaging_web.dart

dependencies:
  firebase_messaging_platform_interface: #^1.0.0
    path: ../firebase_messaging_platform_interface
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  firebase: ^7.0.0
  http_parser: ^3.1.3
  meta: ^1.1.7
  service_worker: ^0.2.4

dev_dependencies:
  pedantic: ^1.8.0
  flutter_test:
    sdk: flutter
  path: ^1.6.2

environment:
  sdk: ">=2.0.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"
