name: cancel_previous
on: [push]
jobs:
  cancel:
    name: "Cancel Previous Runs"
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.3.1
        with:
          workflow_id: >-
            all_plugins.yaml,
            docs.yaml,
            firebase_admob.yaml,
            firebase_auth.yaml,
            firebase_core.yaml,
            firebase_creashlytics.yaml,
            firebase_database.yaml,
            firebase_firestore.yaml,
            firebase_functions.yaml,
            firebase_messaging.yaml,
            firebase_performance.yaml,
            firebase_remote_config.yaml,
            firebase_storage
          access_token: ${{ github.token }}
