name: firebase_storage

on:
  pull_request:
    paths:
      - "packages/firebase_storage/**"
      - ".github/workflows/firebase_storage.yaml"
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"
      - "**/*.md"

env:
  FLUTTERFIRE_PLUGIN_SCOPE: "*firebase_storage*"
  FLUTTERFIRE_PLUGIN_SCOPE_EXAMPLE: "*firebase_storage_example*"

jobs:
  android:
    if: github.event_name == 'pull_request'
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Install Flutter"
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          retry_wait_seconds: 60
          max_attempts: 3
          command: ./.github/workflows/scripts/install-flutter.sh dev
      - name: "Install Tools"
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          retry_wait_seconds: 60
          max_attempts: 3
          command: ./.github/workflows/scripts/install-tools.sh
      - name: "Build Example"
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          retry_wait_seconds: 60
          max_attempts: 3
          command: ./.github/workflows/scripts/build-example.sh android
      - name: "Drive Example"
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          arch: x86_64
          # Firebase Storage works without Google Play Services, so we don't use the `googleapis`
          # emulator target as it's considerably slower on CI.
          target: default
          profile: Nexus 5X
          script: ./.github/workflows/scripts/drive-example.sh android
      - name: Compress Emulator Log
        if: always()
        run: gzip -9 adb-log.txt
        shell: bash
      - name: Upload Emulator Log
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: adb_logs
          path: adb-log.txt.gz

  apple:
    runs-on: macos-latest
    timeout-minutes: 35
    steps:
      - uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Install Flutter"
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          retry_wait_seconds: 60
          max_attempts: 3
          command: ./.github/workflows/scripts/install-flutter.sh dev
      - name: "Install Tools"
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          retry_wait_seconds: 60
          max_attempts: 3
          command: ./.github/workflows/scripts/install-tools.sh && flutter config --enable-macos-desktop
      - name: "Build iOS Example"
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          retry_wait_seconds: 60
          max_attempts: 3
          command: ./.github/workflows/scripts/build-example.sh ios
      - name: "Drive iOS Example"
        run: ./.github/workflows/scripts/drive-example.sh ios
      - name: Compress Simulator Log
        if: always()
        run: gzip -9 simulator.log
      - name: Upload Simulator Log
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: simulator_logs
          path: simulator.log.gz
      - name: "Build MacOS Example"
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          retry_wait_seconds: 60
          max_attempts: 3
          command: ./.github/workflows/scripts/build-example.sh macos
      - name: "Drive MacOS Example"
        run: ./.github/workflows/scripts/drive-example.sh macos

  web:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Install Flutter"
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          retry_wait_seconds: 60
          max_attempts: 3
          command: ./.github/workflows/scripts/install-flutter.sh beta
      - name: "Install Tools"
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          retry_wait_seconds: 60
          max_attempts: 3
          command: ./.github/workflows/scripts/install-tools.sh && flutter config --enable-web
      - name: "Drive Example"
        run: ./.github/workflows/scripts/drive-example.sh web
