name: firebase_functions

on:
  pull_request:
    paths:
      - "packages/firebase_core/**"
      - "packages/cloud_functions/**"
      - ".github/workflows/firebase_functions.yaml"
  push:
    branches:
      - master

env:
  FLUTTERFIRE_PLUGIN_SCOPE: "*cloud_functions*"
  FLUTTERFIRE_PLUGIN_SCOPE_EXAMPLE: "*cloud_functions_example*"

jobs:
  android:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - run: git clone https://github.com/flutter/flutter.git --depth 1 -b stable _flutter
      - run: echo "::add-path::$GITHUB_WORKSPACE/_flutter/bin"
      - name: "Install Tools"
        run: |
          flutter pub global activate melos
          echo "::add-path::$HOME/.pub-cache/bin"
          echo "::add-path::$GITHUB_WORKSPACE/_flutter/.pub-cache/bin"
          echo "::add-path::$GITHUB_WORKSPACE/_flutter/bin/cache/dart-sdk/bin"
      - name: "Bootstrap Workspace"
        run: melos bootstrap
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-${{ github.job }}-${{ hashFiles('**/packages/cloud_functions/**/*.gradle*') }}-${{ hashFiles('**/packages/cloud_functions/**/gradle/wrapper/gradle-wrapper.properties') }}
      - name: "Build Example"
        run: |
          melos exec -c 1 --scope="$FLUTTERFIRE_PLUGIN_SCOPE_EXAMPLE" -- \
            flutter build apk --debug --target=./test_driver/MELOS_PARENT_PACKAGE_NAME_e2e.dart
      - name: "Drive Example"
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          arch: x86_64
          target: google_apis
          profile: Nexus 5X
          script: ./.github/workflows/scripts/drive-android-example.sh

  ios:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - run: git clone https://github.com/flutter/flutter.git --depth 1 -b stable _flutter
      - run: echo "::add-path::$GITHUB_WORKSPACE/_flutter/bin"
      - name: "Install Tools"
        run: |
          flutter pub global activate melos
          echo "::add-path::$HOME/.pub-cache/bin"
          echo "::add-path::$GITHUB_WORKSPACE/_flutter/.pub-cache/bin"
          echo "::add-path::$GITHUB_WORKSPACE/_flutter/bin/cache/dart-sdk/bin"
      - name: "Bootstrap Workspace"
        run: melos bootstrap
      - name: "Build Example"
        run: |
          melos exec -c 1 --scope="$FLUTTERFIRE_PLUGIN_SCOPE_EXAMPLE" -- \
            flutter build ios --no-codesign --simulator --debug --target=./test_driver/MELOS_PARENT_PACKAGE_NAME_e2e.dart
      - name: "Drive Example"
        run: ./.github/workflows/scripts/drive-ios-example.sh

  web:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - run: git clone https://github.com/flutter/flutter.git --depth 1 -b beta _flutter
      - run: echo "::add-path::$GITHUB_WORKSPACE/_flutter/bin"
      - name: "Install Tools"
        run: |
          flutter pub global activate melos
          flutter config --enable-web
          echo "::add-path::$HOME/.pub-cache/bin"
          echo "::add-path::$GITHUB_WORKSPACE/_flutter/.pub-cache/bin"
          echo "::add-path::$GITHUB_WORKSPACE/_flutter/bin/cache/dart-sdk/bin"
      - name: "Bootstrap Workspace"
        run: melos bootstrap
      - name: "Build Example"
        run: |
          melos exec -c 1 --scope="$FLUTTERFIRE_PLUGIN_SCOPE_EXAMPLE" --dir-exists=web -- \
            flutter build web
      - name: "Drive Example"
        run: |
          melos clean && melos bootstrap
          chromedriver --port=4444 &
          melos exec -c 1 --scope="$FLUTTERFIRE_PLUGIN_SCOPE_EXAMPLE" --dir-exists=web -- \
            flutter drive --release --no-pub --verbose-system-logs --browser-name=chrome --target=./test_driver/MELOS_PARENT_PACKAGE_NAME_e2e.dart
