name: firebase_firestore

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "packages/firebase_core/**"
      - "packages/cloud_firestore/**"
      - ".github/workflows/firebase_firestore.yaml"
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"
      - "**.md"

env:
  FLUTTERFIRE_PLUGIN_SCOPE: "*cloud_firestore*"
  FLUTTERFIRE_PLUGIN_SCOPE_EXAMPLE: "*cloud_firestore_example*"

jobs:
  android:
    runs-on: macos-13-xl
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@3f07048e3d294f56e9b90ac5ea2c6f74e9ad0f98
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: subosito/flutter-action@dbf1fa04f4d2e52c33185153d06cdb5443aa189d
        with:
          channel: 'stable'
          cache: true
      - uses: bluefireteam/melos-action@dd3c344d731938d2ab2567a261f54a19a68b5f6a
        with:
          run-bootstrap: false
          melos-version: '3.0.1'
      - name: "Install Tools"
        run: |
          sudo npm i -g firebase-tools@11.28.0
      - name: Start Firebase Emulator
        run: cd ./.github/workflows/scripts && ./start-firebase-emulator.sh
      - name: "E2E Tests"
        uses: reactivecircus/android-emulator-runner@50986b1464923454c95e261820bc626f38490ec0
        timeout-minutes: 30
        with:
          api-level: 30
          arch: x86_64
          target: google_apis
          profile: Nexus 5X
          working-directory: packages/cloud_firestore/cloud_firestore/example
          script: |
            sleep 15
            $ANDROID_HOME/platform-tools/adb logcat '*:D' > adb-log.txt &
            flutter test integration_test/cloud_firestore_e2e_test.dart --dart-define=CI=true

  apple:
    runs-on: macos-13-xl
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@3f07048e3d294f56e9b90ac5ea2c6f74e9ad0f98
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: subosito/flutter-action@dbf1fa04f4d2e52c33185153d06cdb5443aa189d
        with:
          channel: 'stable'
          cache: true
      - uses: bluefireteam/melos-action@dd3c344d731938d2ab2567a261f54a19a68b5f6a
        with:
          run-bootstrap: false
          melos-version: '3.0.1'
      - name: "Install Tools"
        run: |
          sudo npm i -g firebase-tools@11.28.0
      - name: Start Firebase Emulator
        run: cd ./.github/workflows/scripts && ./start-firebase-emulator.sh
      - name: "iOS E2E Tests"
        working-directory: packages/cloud_firestore/cloud_firestore/example
        run: |
          # Boot simulator and wait for System app to be ready.
          # List of available simulators: https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md#installed-simulators
          SIMULATOR="iPhone 14"
          xcrun simctl bootstatus "$SIMULATOR" -b
          xcrun simctl logverbose "$SIMULATOR" enable
          # Sleep to allow simulator to settle.
          sleep 15
          # Uncomment following line to have simulator logs printed out for debugging purposes.
          # xcrun simctl spawn booted log stream --predicate 'eventMessage contains "flutter"' &
          flutter test integration_test/cloud_firestore_e2e_test.dart -d "$SIMULATOR" --dart-define=CI=true
          FLUTTER_DRIVE_EXIT_CODE=$?
          xcrun simctl shutdown "$SIMULATOR"
          exit $FLUTTER_DRIVE_EXIT_CODE
      - name: "Reset Firestore Emulator"
        run: cd ./.github/workflows/scripts && ./reset-firestore-emulator.sh
      - name: "macOS E2E Tests"
        working-directory: packages/cloud_firestore/cloud_firestore/example
        run: |
          sleep 15
          # Uncomment following line to have simulator logs printed out for debugging purposes.
          # xcrun simctl spawn booted log stream --predicate 'eventMessage contains "flutter"' &
          flutter test integration_test/cloud_firestore_e2e_test.dart -d "macos" --dart-define=CI=true
          FLUTTER_DRIVE_EXIT_CODE=$?
          xcrun simctl shutdown "$SIMULATOR"
          exit $FLUTTER_DRIVE_EXIT_CODE

  web:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
        name: Install Node.js 16
        with:
          node-version: "16"
      - uses: actions/setup-java@3f07048e3d294f56e9b90ac5ea2c6f74e9ad0f98
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: subosito/flutter-action@dbf1fa04f4d2e52c33185153d06cdb5443aa189d
        with:
          channel: 'stable'
          cache: true
      - uses: bluefireteam/melos-action@dd3c344d731938d2ab2567a261f54a19a68b5f6a
        with:
          run-bootstrap: false
          melos-version: '3.0.1'
      - name: "Install Tools"
        run: |
          sudo npm i -g firebase-tools@11.28.0
      - name: Start Firebase Emulator
        run: cd ./.github/workflows/scripts && ./start-firebase-emulator.sh
      - name: "E2E Tests"
        working-directory: packages/cloud_firestore/cloud_firestore/example
        # Web devices are not supported for the `flutter test` command yet. As a
        # workaround we can use the `flutter drive` command. Tracking issue:
        # https://github.com/flutter/flutter/issues/66264
        run: |
          chromedriver --port=4444 &
          flutter drive \
            --verbose-system-logs \
            -d web-server \
            --driver=test_driver/integration_test.dart \
            --target=integration_test/cloud_firestore_e2e_test.dart \
            --dart-define=CI=true
